# CiteSeer Link Prediction Configuration
# Out-of-domain task (not used in pre-training)

model_artifact:
  path: 'checkpoints/s5_domain_invariant/best_model.pt'

downstream_task:
  dataset_name: 'CiteSeer'
  task_type: 'link_prediction'
  batch_size: 16
  num_classes: 2
  in_domain: false
  input_dim: 3703
  
  link_prediction:
    negative_sampling_ratio: 1.0
    sampling_strategy: 'uniform'
    max_edges_per_graph: 1500

training:
  epochs: 250
  patience: 25
  optimizer: 'AdamW'
  learning_rate: 0.0005
  weight_decay: 0.0001
  
  scheduler:
    type: 'cosine'
    warmup_epochs: 40
    min_lr_ratio: 0.01
  
  validation_metric: 'val_auc_roc'
  metric_mode: 'max'

fine_tuning_strategy:
  freeze_encoder: true
  unfreeze_epoch: 80
  adaptation_method: 'full'
  
  pretrained_component_lr: 0.00005
  new_component_lr: 0.002

wandb:
  enabled: true
  project_name: 'gnn-evaluation-citeseer-lp'
  run_name: null
  tags: ['citeseer', 'link-prediction', 'out-of-domain']
  notes: 'CiteSeer link prediction - out-of-domain evaluation'

evaluation:
  metrics:
    - 'accuracy'
    - 'f1_score'
    - 'precision'
    - 'recall'
    - 'auc_roc'
    - 'auc_pr'
  
  link_prediction_metrics:
    - 'precision_at_10'
    - 'recall_at_10'
    - 'precision_at_50'
    - 'recall_at_50'
    - 'hit_rate_at_5'
    - 'hit_rate_at_10'

reproducibility:
  seed: 42