name: gnn-pretraining
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults

dependencies:
  # Core ML stack with CUDA support
  - python=3.11
  - pytorch=2.1.*
  - pytorch-cuda=12.1
  - torchvision
  - torchaudio
  
  # PyTorch Geometric ecosystem
  - pyg
  - pytorch-scatter
  - pytorch-sparse
  - pytorch-cluster
  - pytorch-spline-conv
  
  # Core scientific computing
  - numpy>=1.25
  - scipy>=1.12
  - scikit-learn>=1.4
  - pandas>=2.1
  
  # Visualization
  - matplotlib>=3.8
  - seaborn>=0.13
  - plotly>=5.18
  
  # Development tools
  - tqdm>=4.66
  - pyyaml>=6.0
  - pytest>=7.4
  - black
  - isort
  - flake8
  
  # Jupyter ecosystem for research
  - jupyter
  - jupyterlab
  - ipywidgets
  
  # Additional scientific tools
  - networkx>=3.2
  - tensorboard
  
  # Install remaining packages via pip
  - pip
  - pip:
    - wandb>=0.16
    - optuna>=3.5
    - hydra-core>=1.3