name: gnn-pretraining-cpu
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Core ML stack for CPU
  - python=3.11
  - pytorch=2.1.*
  - torchvision
  - torchaudio
  
  # Core scientific computing
  - numpy=1.26.4
  - scipy>=1.12
  - scikit-learn>=1.4
  - pandas>=2.1
  
  # Visualization
  - matplotlib>=3.8
  - seaborn>=0.13
  - plotly>=5.18
  
  # Development tools
  - tqdm>=4.66
  - pyyaml>=6.0
  - pytest>=7.4
  - black
  - isort
  - flake8
  
  # Jupyter ecosystem for research
  - jupyter
  - jupyterlab
  - ipywidgets
  
  # Additional scientific tools
  - networkx>=3.2
  - tensorboard
  
  # Install remaining packages via pip
  - pip
  - pip:
    # PyTorch Geometric CPU-only installation
    - torch-geometric
    - torch-scatter
    - torch-sparse  
    - torch-cluster
    - torch-spline-conv
    # Other
    - wandb>=0.16
    - optuna>=3.5
    - hydra-core>=1.3