# S2: Multi-Task (Contrastive) - NC + GC
# Purpose: Test synergy of purely contrastive tasks (RQ2)

run:
  project_name: 'Graph-Multitask-Learning'
  run_name: 'S2-multi-contrastive-nc-gc'
  entity: null
  tags: ['systematic', 'multi-task', 'contrastive', 'node-contrastive', 'graph-contrastive']
  notes: 'S2: Multi-task contrastive combining Node Contrastive + Graph Contrastive'

data:
  pretrain_datasets: ['MUTAG', 'PROTEINS', 'NCI1', 'ENZYMES']
  batch_size: 32
  domain_balanced_sampling: true
  num_workers: 4
  pin_memory: true
  shuffle: true
  drop_last: true

model:
  hidden_dim: 256
  num_layers: 5
  dropout_rate: 0.2
  enable_augmentations: true  # Required for contrastive learning

optimizer:
  name: 'AdamW'
  lr: 5.0e-4
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.01
  eps: 1.0e-8

scheduler:
  type: 'cosine'
  warmup_epochs: 10
  warmup_fraction: 0.1
  min_lr_ratio: 0.01

training:
  max_epochs: 100
  max_steps: 100000
  validation_freq: 1
  log_freq: 100
  patience: 10
  min_delta: 1.0e-4
  validation_metric: 'val/loss_total'
  metric_mode: 'min'
  checkpoint_dir: './checkpoints/S2_multi_contrastive'
  save_checkpoint_freq: 10
  keep_n_checkpoints: 3
  use_uncertainty_weighting: true  # Multi-task weighting
  uncertainty_init: 0.0
  grad_clip_norm: 1.0
  use_amp: true
  amp_init_scale: 65536.0
  gradient_accumulation_steps: 1

domain_adversarial:
  enabled: false  # Not used in S2

tasks:
  node_feat_mask:
    enabled: false  # Disabled for S2
    weight: 1.0
    mask_rate: 0.15
  link_pred:
    enabled: false  # Disabled for S2
    weight: 1.0
    negative_sampling_ratio: 1.0
  node_contrast:
    enabled: true
    weight: 1.0
    temperature: 0.1
  graph_contrast:
    enabled: true
    weight: 1.0
  graph_prop:
    enabled: false  # Disabled for S2
    weight: 1.0
  domain_adv:
    enabled: false  # Disabled for S2
    weight: 1.0 