exp_name: "s5_all_objectives_da"
pretrain_domains: ["MUTAG", "PROTEINS", "NCI1", "ENZYMES"]
active_tasks: ["node_feat_mask", "link_pred", "node_contrast", "graph_contrast", "graph_prop", "domain_adv"]

