# Base configuration for Node Classification tasks
# This template uses sweep variables for task-specific parameters

exp_name: "${domain_name}_${finetune_strategy}_${pretrained_scheme}"
domain_name: ${domain_name}
pretrained_scheme: ${pretrained_scheme}
finetune_strategy: ${finetune_strategy}

# Task-specific hyperparameters (defined in sweep config)
batch_size: ${batch_size}
epochs: ${epochs}
lr_backbone: ${lr_backbone}
lr_head: ${lr_head}
patience: ${patience}

# Fixed parameters for node classification
task_type: "node_classification"

# Logging and output settings
wandb:
  project: "gnn-pretraining-finetune"
  group: "node_classification"
  tags:
    - ${domain_name}
    - ${pretrained_scheme}
    - ${finetune_strategy}
