# ENZYMES Graph Classification Configuration
# In-domain task (pre-trained on ENZYMES)

model_artifact:
  path: 'checkpoints/s5_domain_invariant/best_model.pt'  # Default to best pre-trained model

downstream_task:
  dataset_name: 'ENZYMES'
  task_type: 'graph_classification'
  batch_size: 32
  num_classes: 6
  in_domain: true  # This dataset was used in pre-training

training:
  epochs: 200
  patience: 15
  optimizer: 'AdamW'
  learning_rate: 0.0001  # Lower LR for pre-trained components
  weight_decay: 0.0005
  
  scheduler:
    type: 'cosine'
    warmup_epochs: 20
    min_lr_ratio: 0.01
  
  validation_metric: 'val_accuracy'
  metric_mode: 'max'

fine_tuning_strategy:
  freeze_encoder: true
  unfreeze_epoch: 50  # Unfreeze after encoder has adapted
  adaptation_method: 'full'
  
  # Component-specific learning rates
  pretrained_component_lr: 0.00005  # Very low for pre-trained components
  new_component_lr: 0.001  # Higher for new classification head

wandb:
  enabled: true
  project_name: 'gnn-evaluation-enzymes'
  run_name: null  # Auto-generated
  tags: ['enzymes', 'graph-classification', 'in-domain']
  notes: 'ENZYMES graph classification - in-domain evaluation'

evaluation:
  metrics:
    - 'accuracy'
    - 'f1_score'
    - 'precision'
    - 'recall'
    - 'auc_roc'

reproducibility:
  seed: 42