# FRANKENSTEIN Graph Classification Configuration
# Out-of-domain task (not used in pre-training)

model_artifact:
  path: 'checkpoints/s5_domain_invariant/best_model.pt'

downstream_task:
  dataset_name: 'FRANKENSTEIN'
  task_type: 'graph_classification'
  batch_size: 16  # Smaller batch due to large graphs
  num_classes: 2
  in_domain: false
  input_dim: 780  # Required for out-of-domain tasks

training:
  epochs: 200
  patience: 20
  optimizer: 'AdamW'
  learning_rate: 0.0001
  weight_decay: 0.001  # Higher weight decay for regularization
  
  scheduler:
    type: 'cosine'
    warmup_epochs: 30
    min_lr_ratio: 0.01
  
  validation_metric: 'val_accuracy'
  metric_mode: 'max'
  
  # Additional regularization for out-of-domain
  gradient_clipping: 1.0

fine_tuning_strategy:
  freeze_encoder: true
  unfreeze_epoch: 75  # Later unfreezing for out-of-domain
  adaptation_method: 'full'
  
  # More conservative learning rates for out-of-domain
  pretrained_component_lr: 0.00001
  new_component_lr: 0.0005

wandb:
  enabled: true
  project_name: 'gnn-evaluation-frankenstein'
  run_name: null
  tags: ['frankenstein', 'graph-classification', 'out-of-domain']
  notes: 'FRANKENSTEIN graph classification - out-of-domain evaluation'

evaluation:
  metrics:
    - 'accuracy'
    - 'f1_score'
    - 'precision'
    - 'recall'
    - 'auc_roc'
    - 'auc_pr'  # Precision-recall AUC for binary classification

reproducibility:
  seed: 42