# PTC_MR Graph Classification Configuration
# Out-of-domain task (not used in pre-training)

model_artifact:
  path: 'checkpoints/s5_domain_invariant/best_model.pt'

downstream_task:
  dataset_name: 'PTC_MR'
  task_type: 'graph_classification'
  batch_size: 32
  num_classes: 2
  in_domain: false
  input_dim: 18  # Corrected dimension based on empirical verification

training:
  epochs: 200
  patience: 15
  optimizer: 'AdamW'
  learning_rate: 0.0001
  weight_decay: 0.0005
  
  scheduler:
    type: 'cosine'
    warmup_epochs: 25
    min_lr_ratio: 0.01
  
  validation_metric: 'val_accuracy'
  metric_mode: 'max'

fine_tuning_strategy:
  freeze_encoder: true
  unfreeze_epoch: 60
  adaptation_method: 'full'
  
  pretrained_component_lr: 0.00002
  new_component_lr: 0.0008

wandb:
  enabled: true
  project_name: 'gnn-evaluation-ptc-mr'
  run_name: null
  tags: ['ptc-mr', 'graph-classification', 'out-of-domain']
  notes: 'PTC_MR graph classification - out-of-domain evaluation'

evaluation:
  metrics:
    - 'accuracy'
    - 'f1_score'
    - 'precision'
    - 'recall'
    - 'auc_roc'
    - 'auc_pr'

reproducibility:
  seed: 42