# Cora Node Classification Configuration
# Out-of-domain task (not used in pre-training)

model_artifact:
  path: 'checkpoints/s5_domain_invariant/best_model.pt'

downstream_task:
  dataset_name: 'Cora'
  task_type: 'node_classification'
  batch_size: 1  # Full-batch for node classification
  num_classes: 7
  in_domain: false
  input_dim: 1433  # Bag-of-words features

training:
  epochs: 300  # More epochs for node classification
  patience: 30
  optimizer: 'AdamW'
  learning_rate: 0.001  # Higher LR for node classification
  weight_decay: 0.0005
  
  scheduler:
    type: 'cosine'
    warmup_epochs: 50
    min_lr_ratio: 0.001
  
  validation_metric: 'val_accuracy'
  metric_mode: 'max'

fine_tuning_strategy:
  freeze_encoder: true
  unfreeze_epoch: 100  # Later unfreezing for complex task
  adaptation_method: 'full'
  
  # Node classification specific settings
  pretrained_component_lr: 0.0001
  new_component_lr: 0.01  # Much higher for new encoder and head

wandb:
  enabled: true
  project_name: 'gnn-evaluation-cora'
  run_name: null
  tags: ['cora', 'node-classification', 'out-of-domain']
  notes: 'Cora node classification - out-of-domain evaluation'

evaluation:
  metrics:
    - 'accuracy'
    - 'f1_score'
    - 'precision'
    - 'recall'
  
  # Node classification specific evaluation
  eval_frequency: 5  # Evaluate every 5 epochs

reproducibility:
  seed: 42