method: grid

program: "../../src/finetune/finetune.py"

config_template: "../templates/finetune.yaml"

parameters:
  domain_name:
    values: ["Cora_NC", "CiteSeer_NC", "Cora_LP", "CiteSeer_LP", "ENZYMES", "PTC_MR"]
  
  finetune_strategy:
    values: ["full_finetune", "linear_probe"]
  
  pretrained_scheme:
    values: 
      - "b1"
      - "b2"
      - "b3"
      - "b4"
      - "s1"
      - "s2"
      - "s3"
      - "s4"
      - "s5"
  
  seed:
    values: [42, 84, 126]