method: grid

program: "src/finetune/finetune.py"
config_template: "configs/finetune/graph_classification_template.yaml"

parameters:
  domain_name:
    values: ["ENZYMES", "PTC_MR"]
  
  pretrained_scheme:
    values: 
      - "b1_from_scratch"
      - "b2_nfm"
      - "b3_nc"
      - "b4_single_domain_all"
      - "s1_multi_task_generative"
      - "s2_multi_task_contrastive"
      - "s3_all_self_supervised"
      - "s4_all_objectives"
      - "s5_all_objectives_da"
  
  finetune_strategy:
    values: ["full_finetune", "linear_probe"]
  
  batch_size:
    values: [32]
  
  epochs:
    values: [100]
  
  lr_backbone:
    distribution: categorical
    values:
      - 1e-4
      - 0.0
  
  lr_head:
    values: [1e-3]
  
  patience:
    values: [10]
  
  seed:
    values: [42, 84, 126]

parameter_combinations:
  - parameters:
      finetune_strategy: "full_finetune"
      lr_backbone: 1e-4
  
  - parameters:
      finetune_strategy: "linear_probe" 
      lr_backbone: 0.0
