method: grid

program: "../../src/pretrain/pretrain.py"

config_template: "../templates/pretrain.yaml"

parameters:
  exp_name:
    values: ["b2", "b3", "b4", "s1", "s2", "s3", "s4", "s5"]

  seed:
    values: [42, 84, 126]