DROPOUT_RATE = 0.2

GNN_HIDDEN_DIM = 256
GNN_NUM_LAYERS = 5

AUGMENTATION_ATTR_MASK_PROB = 0.5
AUGMENTATION_ATTR_MASK_RATE = 0.15
AUGMENTATION_EDGE_DROP_PROB = 0.5
AUGMENTATION_EDGE_DROP_RATE = 0.15
AUGMENTATION_SUBGRAPH_PROB = 0.5
AUGMENTATION_WALK_LENGTH = 10
AUGMENTATION_MIN_NODES_RATIO = 0.3

NODE_FEATURE_MASKING_MASK_RATE = 0.15

DOMAIN_DIMENSIONS = {
    'MUTAG': 7,
    'PROTEINS': 4,
    'NCI1': 37,
    'ENZYMES': 21,
    'FRANKENSTEIN': 780,
    'PTC_MR': 18,
    'Cora': 1433,
    'CiteSeer': 3703
}